### ISSUE TITLE
Complete newbie here

### ISSUE THREAD

**Issue by ayu396** [paulmaunders/delivery-slot-bot#17]
Hi, complete newbie here with no coding experience, just trying to get some groceries. 

Is there a very noob friendly tutorial on how to set this up. I tried following the instructions but it's not making any sense to me. 

I first cloned like so into terminal 
git clone https://github.com/paulmaunders/delivery-slot-bot.git

after that, I copied 
cp config.ini.example config.ini
vim config.ini 

and after that all i get is 

~
~
~
~
~

really confused, sorry for being a noob

**Comment by paulmaunders** [comment]
Vim is quite a tricky text editor to use for a beginner. You could try a vim tutorial to learn the basics, or maybe try editing the config file with something like [Visual Studio Code](https://code.visualstudio.com/) instead. If you install that, then you would then type `code config.ini` instead of `vim config.ini`.

**Comment by git-creat** [comment]
> Vim is quite a tricky text editor to use for a beginner. You could try a vim tutorial to learn the basics, or maybe try editing the config file with something like [Visual Studio Code](https://code.visualstudio.com/) instead. If you install that, then you would then type `code config.ini` instead of `vim config.ini`.

I'm also a noob trying to get this up and running, any tips on how to get going?
