### ISSUE TITLE
Tools to reduce bugs

### ISSUE THREAD

**Issue by andytson** [paulmaunders/delivery-slot-bot#7]
What do you think about introducing tools/language features to reduce semantic bugs?

* typescript - allows type checking though language extensions
* eslint - lints for common usage issues (which most can be auto-fixed)
* prettier - keeps a standard formatting that means there's no need for a manual style review (and can be auto-fixed)
* modularise code and jest - verify code behaviour through tests

**Comment by paulmaunders** [comment]
Sounds good to me 👍🏻

**Comment by paulmaunders** [comment]
I just noticed that the script breaks when you run it after doing a git pull with the new docker stuff. The reason is that we've added a new package **node-schedule** - is it possible to automatically call yarn install if new packages are added, or alternatively can we add a more helpful error message to remind people they need to run it?

**Comment by andytson** [comment]
hmm, it's not common to do that, but can be documented.

**Comment by andytson** [comment]
one thing I guess is, it could be distributed as a npm package, where updating it automatically updates it's own dependencies

**Comment by paulmaunders** [comment]
That could work. Then we can get people to update via npm than through github.

**Comment by andytson** [comment]
All except full typescript done

Instead, as typescript would be better done with npm repository releases to avoid user build step, jsdoc types are being checked with typescript
